# Generated by Django 4.2.1 on 2023-09-20 11:04

import Room.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0002_alter_customuser_managers_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='bhk',
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apartment',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=Room.models.upload_to),
        ),
        migrations.AddField(
            model_name='apartment',
            name='sqft',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apartment',
            name='tenants',
            field=models.PositiveSmallIntegerField(default=2),
            preserve_default=False,
        ),
    ]
