# Generated by Django 4.2.1 on 2023-10-03 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0003_remove_apartment_owner_pkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='owner_pkey',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
